### ISSUE TITLE
NTR: Request for S11 Motile (BODCNVS-847)

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S11#12]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Motile <p><b>Definition</b><p> The life stages of parasitic copepod species commonly referred to as sea lice that are marked by the ability of sub-adult and adult males and females to move freely across the surface of their host. Motile stages are preceded by the chalimus stages in which the organism is attached to its host by a frontal filament.<p><H2> Optional </H2><p><b>Sources/references</b><p> https://waves-vagues.dfo-mpo.gc.ca/Library/359837.pdf<p> <b>Synonym or acronym (AltLabel)</b><p> Motiles (plural)<p><b>Mapping to other terminologies </b><p> Preceded by the lifeStage: http://vocab.nerc.ac.uk/collection/S11/current/S1182/<p>

**Comment by nbekolay** [comment]
Hi Gwen. Just a quick follow-up to see if this life stage will be created soon and available for addition to one of my datasets. Thanks!

**Comment by gwemon** [comment]
@nbekolay Thank you for the prompt. "motile" is already defined in our sub-group vocabulary (http://vocab.nerc.ac.uk/collection/S13/current/S1317/) however, I understand the need to also have the term defined as a life stage.  If I understand correctly, in the case of copepods, this is an umbrella term that can cover several life stages (i.e. naupliar and one copepodid stage), is that right? And there is no specific terms to refer to them apart from calling them "motile" or "free-swimming" stages. However the term "motile" itself is not specific to parasite copepod life stages so if we want to keep the definition as specific as you made it then we would need to make the label more specific: e.g. "parasite copepod motile stage" or "nauplii and copepodids motile stage".
The alternative is to make the definition of the entry more generic so that it can be applied to any biological entity for which the term "motile" is a valid life stage. In that case I would propose:
Preferred label: "motile"
Definition: Term used to refer to one or multiple life stages during which an organism is capable of movement. Examples are naupliar and copepodid motile life-stages of parasitic copepods species commonly known as sea lice."
Once this S11 term is created it can then be used to define a biological entity. i.e. if the biological entity is named elsewhere then we would have the S25 entry:
"biological entity specified elsewhere  [Stage: motile]"
if it is needed in the P01 code then we could have e.g.
"Lepeophtheirus salmonis (WoRMS 35782) [Stage: motile]"
or
"Copepoda (WoRMS 1080) [stage: motile]"
Let me know what you think or please correct anything I got wrong and don't hesitate to involve others in the discussion.

**Comment by nbekolay** [comment]
Hi Gwen,

Thank you for your reply and for laying out the options for me.

That is correct, in the world of salmon aquaculture, the term “motile” is an umbrella term. It refers to mobile pre-adult and adult sea lice that are not fixed to the surface of their hosts (as is the case in the preceding chalimus stages). It excludes the nauplii, copepodid and chalimus stages (I’ve attached an image snipped from https://www.marine.ie/Home/site-area/areas-activity/aquaculture/sea-lice/life-cycle-salmon-louse to help clarify which stages fall under the motile umbrella).

A more specific label should do the trick. I think “motile stages, parasitic copepods” is a viable option (or “motile stages (parasitic copepods)” if that’s a more NERC-friendly format).

Taxa that this would apply to include (but may not be limited to):
Lepeophtheirus salmonis (WORMS 135782)
Caligus clemensi (WORMS 349592)
Caligidae (WORMS 135513)

I’ve listed lifeStage and sex directly in the Occurrence Core for this OBIS-formatted dataset, so won’t need to apply the S25 “…specified elsewhere” term to this iteration. P01 and S25 codes defined for the taxa listed above could be applied to future iterations, though, so introducing them is likely worth the time and effort.

I’ve CC’d the data provider to loop her into the discussion. Krista, if you have any comments to share re: terminology, please let us know.

Thanks again for placing this back in the queue of requests being processed!
-Nick

**Comment by gwemon** [comment]
@nbekolay Hi Nick, Thank you for the link. It says "The chalimus stages moults through two stages which are attached to the fish before becoming a pre-adult or mobile stage and then are able to move around on the surface of the fish and can also swim in the water column.". So if the new term needs to exclude the naupliar and copepodid motile stages then we need to be able to clearly specify "pre-adult" and "adult" in the term as in e.g. "pre-adult and adult motile stage" (I think we need to include the term "stage" here in order to make it clear that this characterises the stage and not the observation) 

One question I have is: can you have pre-adult and adult stages of parasitic copepods that are attached to the host and not motile?

Also, I have just checked what we already have in S11 and the [term sub-adult is there already](http://vocab.nerc.ac.uk/collection/S11/current/S120/) (albeit missing the definition) and has also been used in [combination with "adult"](http://vocab.nerc.ac.uk/collection/S11/current/S1148/) and is also used in the definition of the [chalimus stage](http://vocab.nerc.ac.uk/collection/S11/current/S1182/)
Are the terms "pre-adult" and "sub-adult" used interchangeably in parasitic copepods biology? or is one preferred to the other?

**Comment by nbekolay** [comment]
Hi @gwemon 

I agree. Making the label more precise and descriptive is a feasible solution.

From the reading that I’ve done it appears that “Motiles” in the context of sea lice includes 1 to 4 developmental stages depending on the genus and species of parasitic copepod, so “sub-adult and adult motile stages” would be an ideal fit for a label, I think. “Sub-adult” and “pre-adult” are used interchangeably in aquaculture management circles and in the literature (case in point: “sub-adult” is the term of choice in this 2011 study<https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3035676/> while “preadults” is the preferred term in this 2013 study<https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0073539>), so both terms are appropriate. However, because we’ve already incorporated “sub-adult” into our definition for the life stage “chalimus,” I think we should include it in this definition as well.

Would the following work for a label, alternative label and definition?

Label: “sub-adult and adult motile stages”
Alternative label: “motile (sea lice)”
Definition: “The sub-adult and adult life stages of parasitic copepod species — commonly referred to as “sea lice” — that are marked by the ability of parasites to move freely across the surface of their host or swim freely in the water column. Sea lice motile stages are preceded by the chalimus stages in which the organism is attached to its host by a frontal filament and exclude the free-swimming naupliar and copepodid stages.”

I’ll forward this email to Dr. Laura Sitter, a veterinarian with Fisheries and Oceans Canada, to gauge her thoughts on this label and definition. I’ll let you know if she suggests any changes.

Best,
Nick

**Comment by nbekolay** [comment]
@gwemon 

Dr. Sitter and an epidemiologist colleague of hers have requested that we use "pre-adult" instead of "sub-adult" (or both terms). Could we possibly update the terminology for "chalimus" to include "pre-adult" as well? 

To recap:
Label: **“pre-adult and adult motile stages”**
Alternative label: **“motile (sea lice)”**
Definition: **“The pre-adult and adult life stages of parasitic copepod species — commonly referred to as “sea lice” — that are marked by the ability of parasites to move freely across the surface of their host or swim freely in the water column. Sea lice motile stages are preceded by the chalimus stages in which the organism is attached to its host by a frontal filament and exclude the free-swimming naupliar and copepodid stages.”**

**Comment by gwemon** [comment]
New code S1183	pre-adult and adult motile stages has been queued for publication on the NVS (scheduled for 7AM UTC).
The defintion of the existing code S1182 for "chalimus" has been amended as suggested.

**Comment by nbekolay** [comment]
Thank you, Gwen! This update is greatly appreciated.

**Comment by gwemon** [comment]
New term: http://vocab.nerc.ac.uk/collection/S11/current/S1183/
Modified term: http://vocab.nerc.ac.uk/collection/S11/current/S1183/
