### ISSUE TITLE
NTR: Zooplankton life stages (BODCNVS-881)

### ISSUE THREAD

**Issue by timvdstap** [nvs-vocabs/S11#14]
Hi there,

I am hoping to have a few more life stages added to the NVS, or start the discussion. I'm working on a dataset for zooplankton and the number of life stages recorded is seemingly endless, and sometimes very phylum-specific. Please let me know if you require more information/sources from me, or whether you prefer me creating multiple NTR submissions.

**(PrefLabel)**: Trochophore
[Please enter the label of the term you wish to request]
**Definition**: Free-swimming planktonic marine larva occurring in the first developmental stage of Molluscs and certain marine annelids. The trochophore is the developmental stage prior to veliger. 
**Sources/references**: 
https://www.britannica.com/science/trochophore
https://www.earthlife.net/inverts/gastropod-life-cycle.html

**Synonym or acronym (AltLabel)**: Trochophore larva
**Mapping to external terminologies**: Larvae: http://vocab.nerc.ac.uk/collection/S11/current/S1128/

---

**(PrefLabel)**: Veliger
**Definition**: Developmental stage. Planktonic larva typical of certain mollusks or bivalves. The veliger develops from the trochophore larva. 
**Sources/references**: 
https://www.britannica.com/science/veliger
https://www.earthlife.net/inverts/gastropod-life-cycle.html
**Synonym or acronym (AltLabel)**: Veliger larva
**Mapping to external terminologies**:  Larvae: http://vocab.nerc.ac.uk/collection/S11/current/S1128/

---

**(PrefLabel)**: Paralarva
**Definition**: Early developmental stage of post-embryonic development in some groups of cephalopods. 
**Sources/references**: https://www.ices.dk/sites/pub/Publication%20Reports/Cooperative%20Research%20Report%20(CRR)/CRR324.pdf
**Synonym or acronym (AltLabel)**: Plural form: paralarvae
**Mapping to external terminologies**: Larvae: http://vocab.nerc.ac.uk/collection/S11/current/S1128/

---

**(PrefLabel)**: Eudoxid
**Definition**: Developmental stage found in Siphonophorae. Cormidia are released from the posterior end of the polygastric stage to form free-living sexual units, called the eudoxid stage.
**Sources/references**: 
https://repository.si.edu/handle/10088/25114
https://www.researchgate.net/publication/262774586_Description_of_the_eudoxid_stages_of_Lensia_havock_and_Lensia_leloupi_Cnidaria_Siphonophora_Calycophorae_with_a_review_of_all_known_Lensia_eudoxid_bracts

---

**(PrefLabel)**: Nurse
**Definition**: A developmental stage in the life cycle of doliolids. The nurse stage is the terminal life stage for doliolids, often characterized by a conspicuous tail of gastrozooids. 
**Sources/references**: 
https://aslopubs.onlinelibrary.wiley.com/doi/full/10.1002/lno.11450
https://academic.oup.com/plankt/article/33/7/1139/1555776

---

**(PrefLabel)**: Nectochaete
**Definition**: Developmental larval stage found in Polychaeta species. Planktonic developmental stage bearing functioning parapodia serving locomotion. 
**Sources/references**: 
https://link.springer.com/article/10.1007/s00227-019-3465-9
https://hmr.biomedcentral.com/track/pdf/10.1007/BF02366201.pdf

---

I'm also a little confused about the listed term _copepodites C5 plus adults_, found [here](http://vocab.nerc.ac.uk/collection/S11/current/S1114/). It mentions that this is sometimes also labeled as C6 or CVI stage. From my understanding however, there are 6 copepodite stage _prior_ to the adult stage (see resource linked below). I believe this means that there's no controlled vocabulary for _just_ the C6 life stage? If this is the case, see NTR below:

**(PrefLabel)**: copepodites C6
**Definition**: Final developmental larval stage found in copepodites before reaching the adult stage. 
**Sources/references**:  
https://www2.gov.bc.ca/assets/gov/environment/natural-resource-stewardship/nr-laws-policy/risc/background/key_to_freshwater_calanoid_copepods_of_bc.pdf
https://www.researchgate.net/publication/250217367_Life_cycle_of_Neocalanus_flemingeri_Crustacea_Copepoda_in_the_Oyashio_region_western_subarctic_Pacific_with_notes_on_its_regional_variations

---

Lastly, I'd also be interested how various stages of cnidarian polyps are best classified, such as gastrozooids and gonozooids. Currently there seems to be an overarching classification ('zooids' - http://vocab.nerc.ac.uk/collection/S11/current/S1138/), and I'm wondering whether this should be split up?

**Comment by roy-lowry** [comment]
Certainly my understanding when setting up the vocabs was that there were five copepodite stages followed by the adult, which was also referred to as C6.  This information would have come from the scientists providing us with copepod data.

A quick Google scan provides support for this such as:

https://www.researchgate.net/figure/Developmental-stages-of-the-copepod-Paracyclopina-nana-Adopted-from-Hwang-et-al-2010_fig2_309313656

https://algaeresearchsupply.com/pages/the-biology-of-splashpool-copepods-tigriopus-californicus

http://www.aqua-partners.dk/project-experience/maximus-dk/maximus-technology

The last URL has a diagram clearly stating that C6 = adult

@gwemon is more of a biologist than I'll ever be and may be able to come up with something more authoritative.

**Comment by timvdstap** [comment]
Hi @roy-lowry , 

Very interesting, thanks for sharing! I will confirm with the data provider that they mean the adult life stage, or whether they are under the impression that there are 6 life stages, excluding adult. However, if C6 is indeed adult, would it be classified under S1116 or is it worthwhile considering adding a new term still for this final stage of copepodites (as it appears that currently there is only a term grouping the C5 + adults)?

**Comment by roy-lowry** [comment]
I have been trying to remember with whom I discussed copepod development a decade or so ago when I set up the term - most likely Claudia and/or Gwen in BODC or possibly Roger Harris at PML. After these discussions I had no doubt that there were only 12 copepod development stages and that C6 and adult were exact synonyms. Following this I took great care to ensure that 'C6' or 'CVI' didn't creep into any of the large number of P01 codes for adult copepods.

In my view adding C6 to S11 now would be very unwise as it would create the potential to set up duplicates in P01. Even worse, some new P01 codes for adult copepods could be set up as 'stage adult' whilst others were set up as 'stage C6'. So, I would strongly recommend using S1116.

One thing experience has taught me is that even the most expert of experts can be guilty of using loose terminology that becomes engrained in community language. For example, world-leading deep ocean oceanographers in the 80s and 90s routinely referred to nitrate concentrations whereas what they were measuring was nitrate+nitrite (nitrate is reduced to nitrite for colorimetric analysis and nitrite wasn't determined separately to facilitate a correction). Where they worked nitrite was in such low concentrations that it could be considered non-existent. However, I also found the same loose talk for data from the Humber Estuary where summer nitrites are tens or even hundreds of times higher than nitrates.  

I feel it is the duty of vocabulary managers to dig into the science and identify and correct loose semantics and it is the duty of data managers to ask questions of data originators. It's amazing the misunderstandings that this can unearth. I remember a chief scientist on a cruise and swore blind that the CTD data he took off the ship had been corrected using water bottle salinities. I was pretty sure they hadn't been. I tried telling him this several times leading to at least one blazing row. When I dug a bit deeper it turned out the CTD technician had worked out the salinity correction. However, the computer technician hadn't edited the data given to the PSO. 

I'll leave it to Gwen to deal with the rest of your request.

**Comment by gwemon** [comment]
@timvdstap Thank you for submitting those new life stages. We will review them and add the straightforward ones to S11.
Regarding copepodites, I agree with @roy-lowry that we should avoid creating a separate concept for C6 because C6 is the adult stage. Do you have both "C6" and "adult" labels in your dataset? If you do then I'd be interested to know why your data originators used both terms.

**Comment by timvdstap** [comment]
Hi all, thanks for the input! @gwemon yes I had both C6 and adult labels in my dataset, but have confirmed with the data provider that C6 = adult. 👍

**Comment by gwemon** [comment]
@timvdstap Tim, Thanks for your request and apologies for the time it took to get it processed. I have just added the following terms to the S11 collection:
S1197	nectochaeta
S1196	nurse
S1195	eudoxid
S1194	paralarva
S1193	veliger
S1192	trochophore
They will be available from the NVS after 7:30 London time tomorrow morning. 
You can use this link: http://vocab.nerc.ac.uk/search_nvs/S11/?searchstr=&options=identifier,preflabel,altlabel,status_accepted&rbaddfilter=inc&searchstr2=
And sort by date descending to see the new additions.
Any issues please let me know.
For you question about the Cnidarian stages, this might be something worth bringing up as a separate ticket and asking Cnidarian specialists to help. Maybe create a ticket under the OBIS_VOCAB repo  (https://github.com/nvs-vocabs/OBISVocabs/issues) to gather knowledge before adding to the NVS?

**Comment by timvdstap** [comment]
Hi @gwemon , thank you so much for all your work in this, it's greatly appreciated!!

**Comment by gwemon** [comment]
@timvdstap you're welcome :-) Nicely researched submissions help a lot!
