### ISSUE TITLE
NTR: Request for S11 Late stage of egg

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S11#18]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Late stage of egg <p><b>Definition</b><p> From the end of epiboly to hatching<p><H2> Optional </H2><p><b>Sources/references</b><p> Moser, H. G. (Ed.). (1996). The early stages of fishes in the California Current region. US Department of the Interior, Minerals Management Service, Pacific OCS Region. || Ahlstrom, E.H. and O.P. Ball. (1954). Description of eggs and larvae of jack mackerel (Trachurus symmetricus) and distribution and abundance of larvae in 1950 and 1951. Fish. Bull. 56:209-245. || Kendall, Jr. A.W, Ahlstrom, E.H. and Moser, H.G.(1984). Early life history stages of fishes and their characters, American Society of Ichthyologists and Herpetologists, Special publication 1: 11–22.<p>

**Comment by roswri** [comment]
Suggested term: 

Term name (PrefLabel): Late stage of egg
Definition: An embryonic development stage from the end of gastrulation to hatching.

**Comment by gwemon** [comment]
Entries in S11 target the biological organism/entity rather than the stage, so in this case the entity is the "Late stage egg" and not the "Late stage of egg". It is subtle but it helps us be more consistent and clearer about what the S11 concepts are and how they can be used. Also, for the sake of consistency, we will keep to the plural form of eggs for the time-being, until a decision is taken about changing to all singular forms. So:
PrefLabel: "Late stage eggs"
The definition is fine as is. Thank you @roswri

**Comment by danibodc** [comment]
We have now created the following term:

S1186 - late stage eggs
An embryonic development stage from the end of gastrulation to hatching.

Note that this will not become live on the NVS until ~0730UT tomorrow.

**Comment by danibodc** [comment]
This term is now live on the NVS:
http://vocab.nerc.ac.uk/collection/S11/current/S1186/
